version: '3.8'
services:
  pg1:
    image: postgres:14.5
    container_name: pg1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    # https://github.com/docker-library/postgres/issues/177#issuecomment-655527349
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - "5434:5432"